// Code generated by hertz generator.

package api

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _cqkvMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listkeysMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _statMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _putMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteMw() []app.HandlerFunc {
	// your code...
	return nil
}
